/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesVisitVisaRouteImport } from './routes/services_.visit-visa'
import { Route as ServicesUmrahRouteImport } from './routes/services_.umrah'
import { Route as ServicesStudyVisaRouteImport } from './routes/services_.study-visa'
import { Route as ServicesSaudiKhidmatRouteImport } from './routes/services_.saudi-khidmat'
import { Route as ServicesCrProviderRouteImport } from './routes/services_.cr-provider'
import { Route as ServicesAirlineTicketingRouteImport } from './routes/services_.airline-ticketing'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisitVisaRoute = ServicesVisitVisaRouteImport.update({
  id: '/services_/visit-visa',
  path: '/services/visit-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUmrahRoute = ServicesUmrahRouteImport.update({
  id: '/services_/umrah',
  path: '/services/umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStudyVisaRoute = ServicesStudyVisaRouteImport.update({
  id: '/services_/study-visa',
  path: '/services/study-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSaudiKhidmatRoute = ServicesSaudiKhidmatRouteImport.update({
  id: '/services_/saudi-khidmat',
  path: '/services/saudi-khidmat',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCrProviderRoute = ServicesCrProviderRouteImport.update({
  id: '/services_/cr-provider',
  path: '/services/cr-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAirlineTicketingRoute =
  ServicesAirlineTicketingRouteImport.update({
    id: '/services_/airline-ticketing',
    path: '/services/airline-ticketing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/airline-ticketing': typeof ServicesAirlineTicketingRoute
  '/services/cr-provider': typeof ServicesCrProviderRoute
  '/services/saudi-khidmat': typeof ServicesSaudiKhidmatRoute
  '/services/study-visa': typeof ServicesStudyVisaRoute
  '/services/umrah': typeof ServicesUmrahRoute
  '/services/visit-visa': typeof ServicesVisitVisaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services/airline-ticketing': typeof ServicesAirlineTicketingRoute
  '/services/cr-provider': typeof ServicesCrProviderRoute
  '/services/saudi-khidmat': typeof ServicesSaudiKhidmatRoute
  '/services/study-visa': typeof ServicesStudyVisaRoute
  '/services/umrah': typeof ServicesUmrahRoute
  '/services/visit-visa': typeof ServicesVisitVisaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/services_/airline-ticketing': typeof ServicesAirlineTicketingRoute
  '/services_/cr-provider': typeof ServicesCrProviderRoute
  '/services_/saudi-khidmat': typeof ServicesSaudiKhidmatRoute
  '/services_/study-visa': typeof ServicesStudyVisaRoute
  '/services_/umrah': typeof ServicesUmrahRoute
  '/services_/visit-visa': typeof ServicesVisitVisaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/services/airline-ticketing'
    | '/services/cr-provider'
    | '/services/saudi-khidmat'
    | '/services/study-visa'
    | '/services/umrah'
    | '/services/visit-visa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/services/airline-ticketing'
    | '/services/cr-provider'
    | '/services/saudi-khidmat'
    | '/services/study-visa'
    | '/services/umrah'
    | '/services/visit-visa'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/services_/airline-ticketing'
    | '/services_/cr-provider'
    | '/services_/saudi-khidmat'
    | '/services_/study-visa'
    | '/services_/umrah'
    | '/services_/visit-visa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ServicesAirlineTicketingRoute: typeof ServicesAirlineTicketingRoute
  ServicesCrProviderRoute: typeof ServicesCrProviderRoute
  ServicesSaudiKhidmatRoute: typeof ServicesSaudiKhidmatRoute
  ServicesStudyVisaRoute: typeof ServicesStudyVisaRoute
  ServicesUmrahRoute: typeof ServicesUmrahRoute
  ServicesVisitVisaRoute: typeof ServicesVisitVisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/visit-visa': {
      id: '/services_/visit-visa'
      path: '/services/visit-visa'
      fullPath: '/services/visit-visa'
      preLoaderRoute: typeof ServicesVisitVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/umrah': {
      id: '/services_/umrah'
      path: '/services/umrah'
      fullPath: '/services/umrah'
      preLoaderRoute: typeof ServicesUmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/study-visa': {
      id: '/services_/study-visa'
      path: '/services/study-visa'
      fullPath: '/services/study-visa'
      preLoaderRoute: typeof ServicesStudyVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/saudi-khidmat': {
      id: '/services_/saudi-khidmat'
      path: '/services/saudi-khidmat'
      fullPath: '/services/saudi-khidmat'
      preLoaderRoute: typeof ServicesSaudiKhidmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/cr-provider': {
      id: '/services_/cr-provider'
      path: '/services/cr-provider'
      fullPath: '/services/cr-provider'
      preLoaderRoute: typeof ServicesCrProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/airline-ticketing': {
      id: '/services_/airline-ticketing'
      path: '/services/airline-ticketing'
      fullPath: '/services/airline-ticketing'
      preLoaderRoute: typeof ServicesAirlineTicketingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ServicesAirlineTicketingRoute: ServicesAirlineTicketingRoute,
  ServicesCrProviderRoute: ServicesCrProviderRoute,
  ServicesSaudiKhidmatRoute: ServicesSaudiKhidmatRoute,
  ServicesStudyVisaRoute: ServicesStudyVisaRoute,
  ServicesUmrahRoute: ServicesUmrahRoute,
  ServicesVisitVisaRoute: ServicesVisitVisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
